export const data = [
  {
    id: 1,
    img: "assets/githubProfiler.jpg",
    title: "Github Profiler",
    subtitle: "Personal Project",
    desc: "Displays github user's profile in a beautiful UI. Consumed third party API (Github)",
    link: "https://githubprofilebyprosper.netlify.app/",
  },
  {
    id: 2,
    img: "assets/punterscompanion.png",
    title: "Punters Companion",
    subtitle: "Client Project",
    desc: "A sports betting website, where people subscribe, invest, refer people and earn. this site was built with wordpress",
    link: "https://punterscompanion.com/",
  },
  {
    id: 3,
    img: "assets/tantalizers.png",
    title: "The Tantalizers",
    subtitle: "Client Project",
    desc: "A restaurant website with some cool features. Built with wordpress",
    link: "https://thetantalizersca.com/",
  },
  {
    id: 4,
    img: "assets/reactportfolio.jpg",
    title: "React Portfolio",
    subtitle: "Personal Project",
    desc: "A simple react portfolio app with a cool features and less libraries. React is really cool!!!",
    link: "https://dr0eu.csb.app/",
  },
  {
    id: 5,
    img: "assets/chappelle.jpg",
    title: "Chappelle Daycare",
    subtitle: "Client Project",
    desc: "A Daycare website with a lot of features like online booking, blog, PTA section, etc. Built with wordpress",
    link: "https://chappelledaycare.ca/",
  },
  {
    id: 6,
    img: "assets/gatsby.jpg",
    title: "Gatsby Portfolio",
    subtitle: "Personal Project",
    desc: "Features Dynamic page generation, Page and Static Query, Image optimization etc",
    link: "https://gatsbyappbyprosper.netlify.app/",
  },
  {
    id: 7,
    img: "assets/gtafricamart.jpg",
    title: "GT African Mart",
    subtitle: "Client Project",
    desc: "GT African mart is full e-commerce project. with a lot of features like payment, authentication, security etc. Built with wordpress",
    link: "https://gtafricanmart.ca/",
  },
  {
    id: 7,
    img: "assets/loctech.png",
    title: "Loctech",
    subtitle: "Client Project",
    desc: "Loctech is an eLearning app built with Gatsby JS (Frontend) and Strapi (Backend)",
    link: "https://www.loctechng.com/",
  },
];
