export const data = [
  {
    id: 1,
    img: "assets/githubProfiler.jpg",
    title: "Github Profiler",
    subtitle: "Personal Project",
    desc: "display github user in a beautiful UI. The project is aimed at learning how to consume third party API and use the returned data in my React JS or Next JS app",
    link: "https://githubprofilebyprosper.netlify.app/",
  },
  {
    id: 2,
    img: "assets/punterscompanion.png",
    title: "Punters Companion",
    subtitle: "Client Project",
    desc: "A sports betting website, where people subscribe, invest, refer people and earn. this site was built with wordpress",
    link: "https://punterscompanion.com/",
  },
  {
    id: 3,
    img: "assets/tantalizers.png",
    title: "The Tantalizers",
    subtitle: "Client Project",
    desc: "A restaurant website, based in Canada. People can view their menu, services and portfolio. book or order for products. and make online payment. Built with wordpress",
    link: "https://thetantalizersca.com/",
  },
  {
    id: 4,
    img: "assets/reactportfolio.jpg",
    title: "React Portfolio",
    subtitle: "Personal Project",
    desc: "A simple react portfolio app with a lot of features. Used few libraries for the app. I decided to build this portfolio to learn a lot of features without using too many third party libraries",
    link: "https://dr0eu.csb.app/",
  },
  {
    id: 5,
    img: "assets/chappelle.jpg",
    title: "Chappelle Daycare",
    subtitle: "Client Project",
    desc: "A Daycare website. Features online booking, blog, PTA section, interactive multi-step form and a beautiful responsive design. Built with wordpress",
    link: "https://chappelledaycare.ca/",
  },
  {
    id: 6,
    img: "assets/gatsby.jpg",
    title: "Gatsby Portfolio",
    subtitle: "Personal Project",
    desc: "A simple website with blog. This is my first Gatsby.js project. In this project, I implemented features like Dynamic page generation, Page and Static Query, Image optimization etc",
    link: "https://gatsbyappbyprosper.netlify.app/",
  },
  {
    id: 7,
    img: "assets/gtafricamart.jpg",
    title: "GT African Mart",
    subtitle: "Client Project",
    desc: "GT African mart is full e-commerce project. with a lot of features like payment, authentication, security etc. Built with wordpress",
    link: "https://gtafricanmart.ca/",
  },
];
